import type {
  AgentRunHistoryDetail,
  AgentRunHistorySummary,
} from '../types/agentHistory'

export const agentHistorySummary: AgentRunHistorySummary = {
  id: 'f84cf7c6-4f21-4cf8-a0d9-bef1259e9001',
  conversation_id: '4fa6db52-dd57-44ac-ae46-a20c5ef62772',
  response_mode: 'deep',
  selected_model_tier: 'deep',
  selected_model_name: 'Gemini 3.7 Flash',
  status: 'COMPLETED',
  safe_reason_code: 'COMPLETED',
  step_count: 1,
  retry_count: 0,
  duration_ms: 1450,
  created_at: '2026-08-22T04:00:00Z',
  started_at: '2026-08-22T04:00:00Z',
  completed_at: '2026-08-22T04:00:01Z',
}

export const agentHistoryDetail: AgentRunHistoryDetail = {
  ...agentHistorySummary,
  final_assistant_message_id: '4432dafe-1e4a-43e0-83cb-42e5a4b84021',
  input_tokens: 320,
  output_tokens: 80,
  perception_status: 'COMPLETED',
  perception_reason_code: 'PERCEPTION_COMPLETED',
  policy_decision: 'ALLOWED',
  policy_reason_code: 'REQUEST_SCOPE_AUTHORIZED',
  plan_versions: [
    {
      version: 1,
      change_reason_code: 'PLAN_CREATED',
      planned_step_count: 2,
      created_at: '2026-08-22T04:00:00Z',
    },
  ],
  steps: [
    {
      step_number: 1,
      plan_version: 1,
      plan_step_index: 0,
      action_name: 'TOOL_CALL',
      tool_name: 'portfolio.search_authorized_documents',
      status: 'COMPLETED',
      policy_decision: 'ALLOWED',
      safe_reason_code: 'TOOL_COMPLETED',
      duration_ms: 40,
      observation: {
        status: 'SUCCESS',
        safe_reason_code: 'TOOL_COMPLETED',
        authorized_document_ids: ['5f85df02-f9cf-4638-9abb-c62516048821'],
        authorized_chunk_ids: ['df8e53f4-674c-49f8-9253-ae69fb41bea2'],
        citation_ids: ['ev_1'],
        evidence_count: 1,
        retry_count: 0,
        duration_ms: 35,
      },
    },
  ],
  timeline: [
    {
      sequence: 1,
      stage: 'perception',
      status: 'COMPLETED',
      safe_reason_code: 'PERCEPTION_COMPLETED',
      summary: 'The request was classified without retaining query content.',
      tool_name: null,
      step_number: null,
      duration_ms: 0,
    },
    {
      sequence: 2,
      stage: 'policy',
      status: 'ALLOWED',
      safe_reason_code: 'REQUEST_SCOPE_AUTHORIZED',
      summary: 'Server-owned authorization policy was evaluated.',
      tool_name: null,
      step_number: null,
      duration_ms: 0,
    },
    {
      sequence: 3,
      stage: 'decision',
      status: 'RECORDED',
      safe_reason_code: 'PLAN_CREATED',
      summary: 'Immutable plan version 1 recorded two bounded steps.',
      tool_name: null,
      step_number: null,
      duration_ms: 0,
    },
    {
      sequence: 4,
      stage: 'tool',
      status: 'COMPLETED',
      safe_reason_code: 'TOOL_COMPLETED',
      summary: 'An allow-listed tool action reached a terminal step state.',
      tool_name: 'portfolio.search_authorized_documents',
      step_number: 1,
      duration_ms: 40,
    },
    {
      sequence: 5,
      stage: 'observation',
      status: 'SUCCESS',
      safe_reason_code: 'TOOL_COMPLETED',
      summary: '<img src=x onerror=alert(1)> inert observation summary',
      tool_name: 'portfolio.search_authorized_documents',
      step_number: 1,
      duration_ms: 35,
    },
    {
      sequence: 6,
      stage: 'final',
      status: 'COMPLETED',
      safe_reason_code: 'COMPLETED',
      summary: 'The run reached its recorded lifecycle state.',
      tool_name: null,
      step_number: null,
      duration_ms: 1450,
    },
  ],
}
