from typing import BinaryIO, Protocol

from app.ingestion.contracts import StorageKey, StoredObject


class ObjectStorage(Protocol):
    def put_stream(self, key: StorageKey, stream: BinaryIO) -> StoredObject: ...

    def put_bytes(self, key: StorageKey, data: bytes) -> StoredObject: ...

    def read(self, key: StorageKey) -> bytes: ...

    def delete(self, key: StorageKey) -> None: ...

    def exists(self, key: StorageKey) -> bool: ...
